version: "3.8"
services: 
  database:
    image: postgres:alpine
    ports:
      - '${DATABASE_PORT}:5432'
    environment: 
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '${PGADMIN_LISTEN_PORT}:80'
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      