version: "3.8"
services: 
  database:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - '${DATABASE_PORT}:5432'
    environment: 
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '${PGADMIN_LISTEN_PORT}:80'
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  
  blog:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - database
    environment: 
      DATABASE_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASS: ${DATABASE_PASS}
      DATABASE_NAME: ${DATABASE_NAME}
    ports:
      - 4000:4000